name: Deloy Production
on:
  push:
    branch: ['master']
  pull_request:
    branch: ['master']

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.jobs ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.5.0
          cache: 'npm'
      - name: Create .env file
        run: echo "${{sercrets.ENV_PRODUCTION}}"> .env
      - run: npm i --force
      - run: npm run build 