name: Deloy Production
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.5.0
          cache: 'npm'
      - name: Create .env file
        run: echo "${{secrets.ENV_PRODUCTION}}" > .env
      - run: npm i --force
      - run: npm run build 